export const ADMIN_DELETE_REQUEST = "ADMIN_DELETE_REQUEST";
export const ADMIN_DELETE_SUCCESS = "ADMIN_DELETE_SUCCESS";
export const ADMIN_DELETE_FAIL = "  ADMIN_DELETE_FAIL";

export const USER_UPDATE_BY_ADMIN_REQUEST = "USER_UPDATE_BY_ADMIN_REQUEST";
export const USER_UPDATE_BY_ADMIN_SUCCESS = "USER_UPDATE_BY_ADMIN_SUCCESS";
export const USER_UPDATE_BY_ADMIN_FAIL = "USER_UPDATE_BY_ADMIN_FAIL";
export const USER_UPDATE_BY_ADMIN_RESET = "USER_UPDATE_BY_ADMIN_RESET";

export const PRODUCT_DELETE_BY_ADMIN_REQUEST = "PRODUCT_DELETE_BY_ADMIN_REQUEST";
export const PRODUCT_DELETE_BY_ADMIN_SUCCESS = "PRODUCT_DELETE_BY_ADMIN_SUCCESS";
export const PRODUCT_DELETE_BY_ADMIN_FAIL = "  PRODUCT_DELETE_BY_ADMIN_FAIL";

export const PRODUCT_ADD_BY_ADMIN_REQUEST = "PRODUCT_ADD_BY_ADMIN_REQUEST";
export const PRODUCT_ADD_BY_ADMIN_SUCCESS = "PRODUCT_ADD_BY_ADMIN_SUCCESS";
export const PRODUCT_ADD_BY_ADMIN_FAIL = "  PRODUCT_ADD_BY_ADMIN_FAIL";
export const PRODUCT_ADD_BY_ADMIN_RESET = "PRODUCT_ADD_BY_ADMIN_RESET";

export const PRODUCT_UPDATE_BY_ADMIN_REQUEST = "PRODUCT_UPDATE_BY_ADMIN_REQUEST";
export const PRODUCT_UPDATE_BY_ADMIN_SUCCESS = "PRODUCT_UPDATE_BY_ADMIN_SUCCESS";
export const PRODUCT_UPDATE_BY_ADMIN_FAIL = "  PRODUCT_UPDATE_BY_ADMIN_FAIL";
export const PRODUCT_UPDATE_BY_ADMIN_RESET = "PRODUCT_UPDATE_BY_ADMIN_RESET";

export const GET_ORDERS_BY_ADMIN_REQUEST = "GET_ORDERS_BY_ADMIN_REQUEST";
export const GET_ORDERS_BY_ADMIN_SUCCESS = "GET_ORDERS_BY_ADMIN_SUCCESS";
export const GET_ORDERS_BY_ADMIN_FAIL = "  GET_ORDERS_BY_ADMIN_FAIL";