export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL';

export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST';
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS';
export const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL'

export const PRODUCT_REVIEWS_REQUEST = 'PRODUCT_REVIEWS_REQUEST';
export const PRODUCT_REVIEWS_SUCCESS = 'PRODUCT_REVIEWS_SUCCESS';
export const PRODUCT_REVIEWS_FAIL = 'PRODUCT_REVIEWS_FAIL';
export const PRODUCT_REVIEWS_RESET = 'PRODUCT_REVIEWS_RESET';

export const TOP_RATED_PRODUCT_REQUEST = 'TOP_RATED_PRODUCT_REQUEST';
export const TOP_RATED_PRODUCT_SUCCESS = 'TOP_RATED_PRODUCT_SUCCESS';
export const TOP_RATED_PRODUCT_FAIL = 'PRODUCT_REVIEWS_FAIL';